### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by dthigpen** [SharonLougheed/Equipment-Maintenance-in-VR#7]
Any idea on how  we should go about gamifying the procedure or tutorial?

**Comment by SharonLougheed** [comment]
I really don't like points or numbers. I feel like what would really make
this fun is setting up a scenario where the player has to fix it in a set
amount of time lest something bad happens or the voiceover guy (I'm
imagining they're talking to you by phone or something) starts freaking
out. If any numbers are involved, maybe a clock on the wall or on the
player's phone with a lil alarm. I guess if we did want numerical scores, I
think it'd be better to put them on your phone or something irl rather than
having a UI stuck in your peripheral vision, to keep a sense of realism,
since this is VR.

**Comment by dthigpen** [comment]
I agree with @SharonLougheed here, I think the gamification should be centered around integrating it into the immersion of the environment.

**Comment by Truthseer27** [comment]
There is a rather good chance that these initial users of VR have never used VR in their lives. Their initial cognitive load will be on just figuring out the controls and trying to orient themselves within the environment. I think it would be a good idea to give a couple of minute "warm-up" period where they are given a chance to look around and are directed to travel to a specific location (this could even be untimed...the "timer" starts when they feel they are ready). We could even lead that person through the first step or two (to show what the manipulation controls can do), and they can finish the rest. The "gamification" part seems geared towards a non-novice. Perhaps it can be a scenario type of stretch goal.

**Comment by skystar1991** [comment]
I do not think we have to gamify our VR. We can use some videogame concepts like quest systems for newbies who never use VR before for example, "move to this location", "use the trigger to grab the tool", etc. The primary goal of this VR is to train the newly hired technicians and it is hard to train them in real situation due to limitation of space and equipments.
So, for the tutorial part, we can give the player (or trainee) quests like, 'look at the highlighted spot' and check,  'move to the designated location.' and check, 'grab the tool to do blah blah' and check. something like that. after throwing basic quests, we can make up situations to use proper tools such as using monkey spanner to tighten loosened pipes. and I'm pretty sure we can make these to be finished within 10 mins. and we have to make sure assuming trainees have zero experience on VR.
